name: Build

on:
  push:
    paths:
      - packages/**

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14"
      - run: yarn install
      - run: yarn build
